import rawFormula from "#/config/rating-formula.json";

type RatingFormulaCoefficients = {
	slope: number;
	offset: number;
	r2: number;
	sampleSize: number;
};

// Keyed by exact time control string e.g. "300+0", "600+10".
// Generated by scripts/calibrate-rating-formula.ts.
const RATING_FORMULA = rawFormula as Record<string, RatingFormulaCoefficients>;

const MIN_ELO = 400;
const MAX_ELO = 3000;

function clampElo(raw: number): number {
	return Math.round(Math.min(MAX_ELO, Math.max(MIN_ELO, raw)));
}

// Estimated total seconds for a time control string (e.g. "300+0" → 300).
// Used to find the nearest calibrated time control when an exact match is absent.
function estimatedSeconds(tc: string): number {
	const m = tc.match(/^(\d+)\+(\d+)$/);
	return m ? Number(m[1]) + 40 * Number(m[2]) : 0;
}

function findFormula(timeControl: string): RatingFormulaCoefficients {
	if (RATING_FORMULA[timeControl]) return RATING_FORMULA[timeControl];

	// Fall back to the calibrated time control with the nearest estimated duration.
	const target = estimatedSeconds(timeControl);
	const keys = Object.keys(RATING_FORMULA);
	if (keys.length === 0)
		return { slope: 40, offset: -1200, r2: 0, sampleSize: 0 };

	const nearest = keys.reduce((best, tc) =>
		Math.abs(estimatedSeconds(tc) - target) <
		Math.abs(estimatedSeconds(best) - target)
			? tc
			: best,
	);
	return RATING_FORMULA[nearest];
}

/**
 * Convert game accuracy to Elo using a time-control-specific calibrated formula.
 * Looks up by exact time control string (e.g. "300+0"); falls back to the
 * nearest calibrated time control if an exact match is absent.
 *
 * Coefficients are generated by scripts/calibrate-rating-formula.ts.
 */
export function gameAccuracyToElo(
	accuracyPct: number,
	timeControl: string,
): number {
	const { slope, offset } = findFormula(timeControl);
	return clampElo(slope * accuracyPct + offset);
}

/**
 * Convert accuracy to Elo without a time-control adjustment.
 * Used for dimensional/factor ratings, which aggregate across time controls.
 * Falls back to the "600+0" formula (rapid baseline) if available.
 */
export function accuracyToElo(accuracyPct: number): number {
	const { slope, offset } = findFormula("600+0");
	return clampElo(slope * accuracyPct + offset);
}
