/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as PreviewProgressRouteImport } from './routes/_preview.progress'
import { Route as UsernameGamesGameIdRouteImport } from './routes/$username/games/$gameId'

const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRoute,
} as any)
const PreviewProgressRoute = PreviewProgressRouteImport.update({
  id: '/_preview/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameGamesGameIdRoute = UsernameGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => UsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/progress': typeof PreviewProgressRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/games/$gameId': typeof UsernameGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof PreviewProgressRoute
  '/$username': typeof UsernameIndexRoute
  '/$username/games/$gameId': typeof UsernameGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/_preview/progress': typeof PreviewProgressRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/games/$gameId': typeof UsernameGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/progress'
    | '/$username/'
    | '/$username/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progress' | '/$username' | '/$username/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/_preview/progress'
    | '/$username/'
    | '/$username/games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  PreviewProgressRoute: typeof PreviewProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/_preview/progress': {
      id: '/_preview/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof PreviewProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/games/$gameId': {
      id: '/$username/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/$username/games/$gameId'
      preLoaderRoute: typeof UsernameGamesGameIdRouteImport
      parentRoute: typeof UsernameRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameIndexRoute: typeof UsernameIndexRoute
  UsernameGamesGameIdRoute: typeof UsernameGamesGameIdRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameIndexRoute: UsernameIndexRoute,
  UsernameGamesGameIdRoute: UsernameGamesGameIdRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  PreviewProgressRoute: PreviewProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
